package com.springdemob.model;
// Generated May 17, 2017 7:44:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="test"
)
public class Users  implements java.io.Serializable {


     private Integer UId;
     private String userName;
     private String password;
     private String displayName;

    public Users() {
    }

	
    public Users(String userName, String password) {
        this.userName = userName;
        this.password = password;
    }
    public Users(String userName, String password, String displayName) {
       this.userName = userName;
       this.password = password;
       this.displayName = displayName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="u_id", unique=true, nullable=false)
    public Integer getUId() {
        return this.UId;
    }
    
    public void setUId(Integer UId) {
        this.UId = UId;
    }

    
    @Column(name="user_name", nullable=false, length=100)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="password", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="display_name", length=100)
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }




}


